export const CREATE_POST_ERROR = 'CREATE_POST_ERROR';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const REQUEST_POSTS = 'REQUEST_POSTS';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const EDIT_POST_START = 'EDIT_POST_START';
export const EDIT_POST_END = 'EDIT_POST_END';
